---
- name: "configuration play."
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    #   - name: "wait 600 seconds for target connection to become reachable/usable."
    #     # Your code here

    - name: "install python for Ansible."
      # Your code here
      apt:
        name: python3
        state: latest
        update_cache: yes

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    ENVIRONMENT: production
    - TYPEORM_CONNECTION: "postgres"
    - TYPEORM_ENTITIES: "/home/ubuntu/app/dist/modules/domain/**/*.entity{.ts,.js}"
    - TYPEORM_MIGRATIONS: "/home/ubuntu/app/dist/migrations/*.js"
    - TYPEORM_MIGRATIONS_DIR: "/home/ubuntu/app/dist/migrations"
    - TYPEORM_PORT: 5432
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"

  roles:
    # Your code here
    - configure-server
