AWSTemplateFormatVersion: 2010-09-09

Description: Infrastructure creation for Monitoring tools(Prometheus)

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: udacity
      ImageId: "ami-052efd3df9dad4825"
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: "Prometheus-intance"
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "9090"
          ToPort: "9090"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "9093"
          ToPort: "9093"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "9100"
          ToPort: "9100"
          CidrIp: 0.0.0.0/0
